package org.mograrep.model;

import java.util.List;

import org.semanticweb.owlapi.model.IRI;
/**
 * Interface to generate ContextData, given an IRI chain (parents and child of some context)
 * 
 * @author schlafli
 *
 */
public interface InstanceDataGenerator {
	
	/**
	 * Get the name for this type of InstanceDataGenerator
	 * @return The name of the IDG
	 */
	public String getGeneratorName();
	
	
	
	/**
	 * Determines how applicable this InstanceDataGenerator is to the given IRI chain.
	 * 
	 * @param chain The chain of IRIs leading to the concept for which we want to generate data
	 * @return Returns a value [0..1], 1.0 corresponding to a perfect match, and 0.0 a complete mismatch
	 */
	public double matchType(List<IRI> chain);
	
	/**
	 * Generates a list of data for a given context chain
	 * 
	 * @param chain The list of parents leading to the given CI
	 * @return A list of ContextData, with values generated by this InstanceDataGenerator
	 */
	public List<ContextData> generateData(List<IRI> chain);
	
	
}
